public enum EventType {
    GameOver,
    GameTrue,
    StartGame,
    Attack,
    EnemyPrepare,
    UpdateEnemyMap,
    ExitOnlineGame,
    PlayerExit,
    EnemyToFalse,
    MenuStartButtonClick,
    PauseStartButtonClick,
    PauseRestartButtonClick,
    PauseHomeButtonClick,
    GamePauseButtonButtonClick,
    GameOverRestartButtonClick,
    GameOverHomeButtonClick,
}